export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR'

export const FETCH_PRODUCT_START = 'FETCH_PRODUCT_START'
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS'
export const FETCH_PRODUCT_NOT_EXIS = 'FETCH_PRODUCT_NOT_EXIS'
export const FETCH_PRODUCT_ERROR = 'FETCH_PRODUCT_ERROR'

export const ADD_TO_CART = 'ADD_TO_CART'
export const ADD_TO_CART_NOT_EXIST = 'ADD_TO_CART_NOT_EXIST'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const ADD_TO_CART_ERROR = 'ADD_TO_CART_ERROR'
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS'

export const SET_FILTER = 'SET_FILTER'
export const SET_QUERY = 'SET_QUERY'

